name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  setup:
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - shell: bash
        run: pnpm install

  typecheck:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: 
      - setup
    steps:
      - name: Typecheck
        run: pnpm run typecheck

  quality:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: 
      - setup
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest

      - name: Run Biome
        run: biome ci .

      - name: Something tsomething
        steps:
          - name: Something
            run: echo "Something"
          - name: Something else
            run: echo "Something else"
